services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.39.6
    restart: unless-stopped

    ports:
      - "5678:5678"

    environment:
      N8N_UNVERIFIED_PACKAGES_ENABLED: "false"
      TZ: Asia/Dubai
      GENERIC_TIMEZONE: Asia/Dubai
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"

    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
