"""create leads table

Revision ID: 075e79466b63
Revises: 
Create Date: 2026-09-23 16:00:41.190345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '075e79466b63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('company', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=150), nullable=True),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'validated'"), nullable=False),
    sa.Column('workflow_execution_id', sa.String(length=64), nullable=True),
    sa.Column('score', sa.SmallInteger(), nullable=True),
    sa.Column('temperature', sa.String(length=8), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('website', 'form', 'api', 'facebook_ads', 'extension', 'playwright', 'manual')", name=op.f('ck_leads_source_value')),
    sa.CheckConstraint("temperature IS NULL OR temperature IN ('hot', 'warm', 'cold')", name=op.f('ck_leads_temperature_value')),
    sa.CheckConstraint('occurrence_count >= 1', name=op.f('ck_leads_occurrence_count_positive')),
    sa.CheckConstraint('score IS NULL OR score BETWEEN 0 AND 100', name=op.f('ck_leads_score_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
